var hierarchy =
[
    [ "sqlcpp::Builder", "structsqlcpp_1_1Builder.html", [
      [ "sqlcpp::Assign", "structsqlcpp_1_1Assign.html", null ],
      [ "sqlcpp::Assigns", "structsqlcpp_1_1Assigns.html", null ],
      [ "sqlcpp::BlobValue", "structsqlcpp_1_1BlobValue.html", null ],
      [ "sqlcpp::Check", "structsqlcpp_1_1Check.html", null ],
      [ "sqlcpp::Column", "structsqlcpp_1_1Column.html", null ],
      [ "sqlcpp::CondBetween", "structsqlcpp_1_1CondBetween.html", null ],
      [ "sqlcpp::CondCmp", "structsqlcpp_1_1CondCmp.html", null ],
      [ "sqlcpp::CondIn", "structsqlcpp_1_1CondIn.html", null ],
      [ "sqlcpp::CondNotIn", "structsqlcpp_1_1CondNotIn.html", null ],
      [ "sqlcpp::CondOp", "structsqlcpp_1_1CondOp.html", null ],
      [ "sqlcpp::CondRaw", "structsqlcpp_1_1CondRaw.html", null ],
      [ "sqlcpp::Condition", "structsqlcpp_1_1Condition.html", null ],
      [ "sqlcpp::Delete", "structsqlcpp_1_1Delete.html", null ],
      [ "sqlcpp::Field", "structsqlcpp_1_1Field.html", null ],
      [ "sqlcpp::FieldLike", "structsqlcpp_1_1FieldLike.html", null ],
      [ "sqlcpp::ForeignKey", "structsqlcpp_1_1ForeignKey.html", null ],
      [ "sqlcpp::From", "structsqlcpp_1_1From.html", null ],
      [ "sqlcpp::Froms", "structsqlcpp_1_1Froms.html", null ],
      [ "sqlcpp::FuncField", "structsqlcpp_1_1FuncField.html", null ],
      [ "sqlcpp::GroupBy", "structsqlcpp_1_1GroupBy.html", null ],
      [ "sqlcpp::Having", "structsqlcpp_1_1Having.html", null ],
      [ "sqlcpp::Index", "structsqlcpp_1_1Index.html", null ],
      [ "sqlcpp::Insert", "structsqlcpp_1_1Insert.html", null ],
      [ "sqlcpp::NullValue", "structsqlcpp_1_1NullValue.html", null ],
      [ "sqlcpp::OrderBy", "structsqlcpp_1_1OrderBy.html", null ],
      [ "sqlcpp::OrderByField", "structsqlcpp_1_1OrderByField.html", null ],
      [ "sqlcpp::PrimaryKey", "structsqlcpp_1_1PrimaryKey.html", null ],
      [ "sqlcpp::RawField", "structsqlcpp_1_1RawField.html", null ],
      [ "sqlcpp::RawFrom", "structsqlcpp_1_1RawFrom.html", null ],
      [ "sqlcpp::RawValue", "structsqlcpp_1_1RawValue.html", null ],
      [ "sqlcpp::Select", "structsqlcpp_1_1Select.html", null ],
      [ "sqlcpp::Table", "structsqlcpp_1_1Table.html", null ],
      [ "sqlcpp::Unique", "structsqlcpp_1_1Unique.html", null ],
      [ "sqlcpp::Update", "structsqlcpp_1_1Update.html", null ],
      [ "sqlcpp::Value", "structsqlcpp_1_1Value.html", null ],
      [ "sqlcpp::ValueLike", "structsqlcpp_1_1ValueLike.html", null ],
      [ "sqlcpp::VarValue", "structsqlcpp_1_1VarValue.html", [
        [ "sqlcpp::IndexedVarValue", "structsqlcpp_1_1IndexedVarValue.html", null ]
      ] ],
      [ "sqlcpp::Where", "structsqlcpp_1_1Where.html", null ]
    ] ],
    [ "sqlcpp::CondOpType", "structsqlcpp_1_1CondOpType.html", null ],
    [ "sqlcpp::InsertValues", "structsqlcpp_1_1InsertValues.html", null ],
    [ "sqlcpp::F::NamedFunc", "structsqlcpp_1_1F_1_1NamedFunc.html", null ],
    [ "sqlcpp::Type", "structsqlcpp_1_1Type.html", null ],
    [ "sqlcpp::VarBuilder", "structsqlcpp_1_1VarBuilder.html", [
      [ "sqlcpp::Cond", "structsqlcpp_1_1Cond.html", [
        [ "sqlcpp::CondBetween", "structsqlcpp_1_1CondBetween.html", null ],
        [ "sqlcpp::CondCmp", "structsqlcpp_1_1CondCmp.html", null ],
        [ "sqlcpp::CondIn", "structsqlcpp_1_1CondIn.html", null ],
        [ "sqlcpp::CondNotIn", "structsqlcpp_1_1CondNotIn.html", null ],
        [ "sqlcpp::CondOp", "structsqlcpp_1_1CondOp.html", null ],
        [ "sqlcpp::CondRaw", "structsqlcpp_1_1CondRaw.html", null ]
      ] ],
      [ "sqlcpp::Condition", "structsqlcpp_1_1Condition.html", null ],
      [ "sqlcpp::Field", "structsqlcpp_1_1Field.html", null ],
      [ "sqlcpp::FieldLike", "structsqlcpp_1_1FieldLike.html", null ],
      [ "sqlcpp::FuncField", "structsqlcpp_1_1FuncField.html", null ],
      [ "sqlcpp::GroupBy", "structsqlcpp_1_1GroupBy.html", null ],
      [ "sqlcpp::Having", "structsqlcpp_1_1Having.html", null ],
      [ "sqlcpp::OrderBy", "structsqlcpp_1_1OrderBy.html", null ],
      [ "sqlcpp::OrderByField", "structsqlcpp_1_1OrderByField.html", null ],
      [ "sqlcpp::RawField", "structsqlcpp_1_1RawField.html", null ],
      [ "sqlcpp::Select", "structsqlcpp_1_1Select.html", null ],
      [ "sqlcpp::ValueLike", "structsqlcpp_1_1ValueLike.html", null ],
      [ "sqlcpp::VarValue", "structsqlcpp_1_1VarValue.html", null ],
      [ "sqlcpp::Where", "structsqlcpp_1_1Where.html", null ]
    ] ],
    [ "sqlcpp::VarMap", "structsqlcpp_1_1VarMap.html", null ],
    [ "sqlcpp::version", "structsqlcpp_1_1version.html", null ]
];